parent: "configs/scannetpp_base.yaml"
save_step: 100

frame_start: 0
frame_step: 0
frame_num: -1

# dataset params:
source_path: "data/ScanNetpp/scene0050_00"
save_path: "output/dataset/ScanNetpp/scene0050_00"
